<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "heartbeat".
 *
 * @property string $id
 * @property integer $user_id
 * @property string $branch
 * @property string $entity
 * @property integer $is_debugging
 * @property integer $is_write
 * @property string $language
 * @property string $project
 * @property integer $time
 * @property integer $time_micro
 * @property string $type
 * @property string $aliasModel
 */
abstract class Heartbeat extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'heartbeat';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['id', 'entity', 'is_write', 'time', 'time_micro'], 'required'],
            [['user_id', 'is_debugging', 'is_write', 'time', 'time_micro'], 'integer'],
            [['id', 'branch', 'entity', 'language', 'project', 'type'], 'string', 'max' => 255]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', 'ID'),
            'user_id' => Yii::t('app', 'User ID'),
            'branch' => Yii::t('app', 'Branch'),
            'entity' => Yii::t('app', 'Entity'),
            'is_debugging' => Yii::t('app', 'Is Debugging'),
            'is_write' => Yii::t('app', 'Is Write'),
            'language' => Yii::t('app', 'Language'),
            'project' => Yii::t('app', 'Project'),
            'time' => Yii::t('app', 'Time'),
            'time_micro' => Yii::t('app', 'Time Micro'),
            'type' => Yii::t('app', 'Type'),
        ];
    }


    
    /**
     * @inheritdoc
     * @return \app\models\query\HeartbeatQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \app\models\query\HeartbeatQuery(get_called_class());
    }


}
